--datos iniciales de la bbbdd de la tienda de discos
	
	DELETE FROM USUARIOS;
	
	INSERT INTO USUARIOS(DNI, NOMBRE, APELLIDOS, CORREO, CONTRASENIA)                                                            
	VALUES ('12345678A','PEPE', 'DE PRUEBA', 'EJEMPLO@HOTMAIL.COM', '1234');
	
	INSERT INTO USUARIOS(DNI, NOMBRE, APELLIDOS, CORREO, CONTRASENIA) 
	VALUES ('12345678B','sean', 'booth', 'sean@gmail.com', 'pestillo');
	
	INSERT INTO USUARIOS(DNI, NOMBRE, APELLIDOS, CORREO, CONTRASENIA) 
	VALUES ('12345678C','a', 'a', 'a', 'a');
	
	COMMIT;
	
	DELETE FROM DISCOS;
	DELETE FROM CDS;
	DELETE FROM VINILOS;
	DELETE FROM CASSETTES;
	
	--CDS
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('5555', 'kelela', 'contact', '12345678C');
	INSERT INTO CDS
	VALUES('111', '5555');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('6666', 'big thief', 'masterpiece', '12345678C');
	INSERT INTO CDS
	VALUES('222', '6666');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('8888', 'autechre', 'exai', '12345678A');
	INSERT INTO CDS
	VALUES ('AAA', '8888');
	
	COMMIT;
	
	--Vinilos
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('2324', 'kelela', 'contact', '12345678C');
	INSERT INTO VINILOS
	VALUES(7, '2324');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('4567', 'caroline polacheck', 'Welcome to my Island', '12345678C');
	INSERT INTO VINILOS
	VALUES(7, '4567');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('9090', 'Charli XCX', 'Crash', '12345678A');
	INSERT INTO VINILOS
	VALUES (12, '9090');
	
	COMMIT;
	
	--Cassettes
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('1212', 'Futuro Terror', 'Precipicio', '12345678C');
	INSERT INTO CASSETTES
	VALUES('N', '1212');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('6664', 'La Plata', 'Desorden', '12345678C');
	INSERT INTO CASSETTES
	VALUES('S', '6664');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('8123', 'autechre', 'exai', '12345678A');
	INSERT INTO CASSETTES
	VALUES ('S', '8123');
	
	COMMIT;