--datos iniciales de la bbbdd de la tienda de discos
	
	DELETE FROM USUARIOS;
	
	INSERT INTO USUARIOS(DNI, NOMBRE, APELLIDOS, CORREO, CONTRASENIA)                                                            
	VALUES ('12345678A','PEPE', 'DE PRUEBA', 'EJEMPLO@HOTMAIL.COM', '1234');
	
	INSERT INTO USUARIOS(DNI, NOMBRE, APELLIDOS, CORREO, CONTRASENIA) 
	VALUES ('12345678B','sean', 'booth', 'sean@gmail.com', 'pestillo');
	
	INSERT INTO USUARIOS(DNI, NOMBRE, APELLIDOS, CORREO, CONTRASENIA) 
	VALUES ('12345678C','a', 'a', 'a', 'a');
	
	COMMIT;
	
	DELETE FROM DISCOS;
	DELETE FROM CDS;
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('5555', 'big thief', 'masterpiece', '12345678C');
	INSERT INTO CDS
	VALUES('111', '5555');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('6666', 'big thief', 'masterpiece', '12345678C');
	INSERT INTO CDS
	VALUES('222', '6666');
	
	INSERT INTO DISCOS(ID_DISCO, NOMBRE_BANDA, TITULO, DNI_USUARIO)
	VALUES ('8888', 'autechre', 'exai', '12345678A');
	INSERT INTO CDS
	VALUES ('AAA', '8888');
	
	COMMIT;