--PATRICIO CIFREDO 1º DAW-B
-- BASE DE DATOS PARA TIENDA DE DISCOS
--CREATE DATABASE TIENDA_DISCOS;
--USE TIENDA_DISCOS;

	DROP TABLE USUARIOS CASCADE CONSTRAINTS;
	CREATE TABLE USUARIOS
	(
	DNI VARCHAR (9) CONSTRAINT PK_USUARIO PRIMARY KEY,
	NOMBRE VARCHAR (20) NOT NULL,
	APELLIDOS VARCHAR (40) NOT NULL,
	CORREO VARCHAR (50) CONSTRAINT CK_CORREO_UNICO NOT NULL,
	CONTRASENIA VARCHAR (50) NOT NULL
	);
	
	ALTER TABLE USUARIOS ADD CONSTRAINT CORREO_UNIQUE UNIQUE (CORREO);
	
	----------------------------------------------------------------------
	
	
	DROP TABLE DISCOS CASCADE CONSTRAINTS;
	CREATE TABLE DISCOS 
	(
	ID_DISCO VARCHAR(4),
	TITULO VARCHAR (40) NOT NULL,
	NOMBRE_BANDA VARCHAR (40) NOT NULL,
	ANIO_PUBLICACION NUMBER(4) NOT NULL,
	PRECIO NUMBER(4,2) NOT NULL,
	SELLO VARCHAR (20) NOT NULL,
	DNI_USUARIO VARCHAR (9)
	);
	
	ALTER TABLE DISCOS ADD CONSTRAINT PK_DISCOS PRIMARY KEY (ID_DISCO);
	ALTER TABLE DISCOS ADD CONSTRAINT FK_DISCOS_DNI_USUARIO FOREIGN KEY (DNI_USUARIO) 
	REFERENCES USUARIOS(DNI) ON DELETE CASCADE;
	ALTER TABLE DISCOS ADD CONSTRAINT CK_ANIOS_PERMITIDOS CHECK(ANIO_PUBLICACION>=1955);
	
	
	----------------------------------------------------------------------
	
	
	DROP TABLE VINILOS CASCADE CONSTRAINTS;
	CREATE TABLE VINILOS 
	(
	REVOLUCIONES NUMBER(2) NOT NULL,
	PULGADAS NUMBER(2) NOT NULL,
	ID_DISCO VARCHAR(4)
	);
	
	ALTER TABLE VINILOS ADD CONSTRAINT FK_VINILOS FOREIGN KEY (ID_DISCO) 
	REFERENCES DISCOS(ID_DISCO) ON DELETE CASCADE;
	ALTER TABLE VINILOS ADD CONSTRAINT CK_VIN_PULGADAS CHECK (PULGADAS IN (12, 7));
	ALTER TABLE VINILOS ADD CONSTRAINT CK_VIN_REVOLUCIONES CHECK (REVOLUCIONES IN (33, 45));
	
	
	----------------------------------------------------------------------
	
	
	
	DROP TABLE CDS CASCADE CONSTRAINTS;
	CREATE TABLE CDS
	(
	COD_DESC_DIGITAL VARCHAR(3) NOT NULL,
	ID_DISCO VARCHAR(4)
	);
	
	ALTER TABLE CDS ADD CONSTRAINT FK_CDS FOREIGN KEY (ID_DISCO) 
	REFERENCES DISCOS(ID_DISCO) ON DELETE CASCADE;
	ALTER TABLE CDS ADD CONSTRAINT COD_UNICO UNIQUE (COD_DESC_DIGITAL);
	
	
	----------------------------------------------------------------------
	
	
	DROP TABLE CASSETTES CASCADE CONSTRAINTS;
	CREATE TABLE CASSETTES
	(
	SEGUNDA_MANO VARCHAR(1) NOT NULL,
	ID_DISCO VARCHAR(4)
	);
	
	ALTER TABLE CASSETTES ADD CONSTRAINT FK_CASSETTES FOREIGN KEY (ID_DISCO) 
	REFERENCES DISCOS ON DELETE CASCADE;
	ALTER TABLE CASSETTES ADD CONSTRAINT CK_SEGUNDA_MANO CHECK (SEGUNDA_MANO IN ('T', 'F'));